name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: List environmen vars
        run: env
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run script
        run: |
          python script.py
          git add counter
          git commit -m "Increment counter"
          git push
        env:
          DUMMY_SECRET: ${{ secrets.DUMMY_SECRET }}
          DUMMY_VAR: ${{ vars.DUMMY_VAR }}
